create database AdeNot
use AdeNot


CREATE TABLE TYPES(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(30),
ICON VARCHAR(30)
)

CREATE TABLE CATEGORIES(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(50)
)


Create table Pizzas(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(50),
DESCRIPTION VARCHAR(MAX),
CategoryId Int References CATEGORIES(ID)
)

create table Images(
ID INT PRIMARY KEY IDENTITY,
[Name] nvarchar(40),
PizzaId int references Pizzas(ID)

)

CREATE TABLE PIZZATYPES(
ID INT PRIMARY KEY IDENTITY,
PIZZAID INT REFERENCES Pizzas(ID),
TYPEID INT REFERENCES TYPES(ID)
)

CREATE TABLE SIZES(
ID INT PRIMARY KEY IDENTITY,
SIZE VARCHAR(20),
SIZEVALUE INT)

CREATE TABLE CURRENCIES(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(MAX)
)
CREATE TABLE INNERGREDIENTS(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(30)
)

CREATE TABLE PRICES(
ID INT PRIMARY KEY IDENTITY,
PRICE DECIMAL(5,2),
PIZZAID INT REFERENCES PIZZAS(ID),
SIZEID INT REFERENCES SIZES(ID),
CURRENCYID INT REFERENCES CURRENCIES(ID)
)
CREATE TABLE PIZZAINNERGRADIENTS(
ID INT PRIMARY KEY IDENTITY,
PIZZAID INT REFERENCES PIZZAS(ID),
INNERGRADIENTID INT REFERENCES INNERGREDIENTS(ID)
)

SELECT *
FROM Pizzas  
INNER JOIN PRICES 
ON Pizzas.ID=PRICES.PIZZAID


select *from Pizzas where id=1
select * from pizzas 
inner join prices
on Pizzas.id=PRICES.PIZZAID



Create table PizzaUp(
id int primary key identity,
Name Nvarchar(30),
InnergredientId int references INNERGREDIENTS(ID),
pizzaSize nvarchar(30),
PizzaPrice Decimal(5,2)

)

INSERT INTO PizzaUp values('asa',1,'orta',5)